// <auto-generated />
using System;
using Cuenta_Movimiento.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuenta_Movimiento.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cuenta_Movimiento.Models.Data.CuentaModel", b =>
                {
                    b.Property<int>("cuenta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cuenta_id"), 1L, 1);

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("numero_cuenta")
                        .HasColumnType("int");

                    b.Property<float>("saldo_inicial")
                        .HasColumnType("real");

                    b.Property<string>("tipo_cuenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("cuenta_id");

                    b.HasIndex("numero_cuenta")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Cuenta_Movimiento.Models.Data.MovimientoModel", b =>
                {
                    b.Property<int>("movimiento_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("movimiento_id"), 1L, 1);

                    b.Property<int?>("cuenta_id")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<float>("saldo")
                        .HasColumnType("real");

                    b.Property<string>("tipo_movimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("movimiento_id");

                    b.HasIndex("cuenta_id");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Cuenta_Movimiento.Models.Data.MovimientoModel", b =>
                {
                    b.HasOne("Cuenta_Movimiento.Models.Data.CuentaModel", "cuenta")
                        .WithMany()
                        .HasForeignKey("cuenta_id");

                    b.Navigation("cuenta");
                });
#pragma warning restore 612, 618
        }
    }
}
