version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      SA_PASSWORD: serverpassword
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - my_network

  api:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network: